[package]
name = "aoc2022"
version = "0.1.0"
authors = ["Blaine <rishi1998@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.8.0"
nom = "7.1.1"
regex = "1.7.0"

